format = """
$character\
$os\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$shell
"""

add_newline = false

[line_break]
disabled = true

[os.symbols]
Macos = " "
Raspbian = " "
Ubuntu = " "
Windows = " "
Redhat = "󱄛 "
Arch = "󰣇 "
Debian = " "
Android = " "
Amazon = " "
Linux = " "
Unknown = " "

[character]
disabled = true

[os]
format = "[$symbol](bold white)"
style = "bold blue"
disabled = false

[hostname]
ssh_only = false
ssh_symbol = ' '
format = ' [on](bold italic fg:white) [$ssh_symbol](bold blue)[$hostname](bold bright-blue) '
trim_at = '.companyname.com'
disabled = false

[username]
style_user = 'bold fg:#AAF0D1'
style_root = 'bold red'
format = '[$user]($style)'
disabled = false
show_always = true

[python]
symbol = ' '
[ruby]
symbol = ' '
[rust]
symbol = ' '
[php]
symbol = ' '
[nodejs]
symbol = '󰎙 '
[java]
symbol = ' '
[golang]
symbol = '󰟓 '
[kotlin]
symbol = ' '
[rlang]
symbol = "󰟔 "
[swift]
symbol = " "
[c]
symbol = " "
[gradle]
symbol = " "
[git_branch]
symbol = ' '
[kubernetes]
symbol = '󱃾 '
[docker_context]
symbol = "󰡨 "
[aws]
symbol = "󰸏 "
[azure]
symbol = " "
[gcloud]
symbol = "󱇶 "
